// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://snbbzjcgtjdjdovurxjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuYmJ6amNndGpkamRvdnVyeGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODM4ODIsImV4cCI6MjA2MDc1OTg4Mn0._XpHpLAx6wQYG4jCoCEvZeJ9SCQVDkaziPug3FSu7P0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);